# Generated by Django 4.0 on 2021-12-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_normativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='date_normativa',
            table='busqueda_normativa',
        ),
    ]
