# Generated by Django 3.2 on 2021-08-25 15:49

from django.db import migrations, models
import django.db.models.deletion
import normas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(help_text='Nombre de Categoria', max_length=200, verbose_name='Nombre de la Categoria')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name_plural': '0.Normas - Tipo de Uso',
            },
        ),
        migrations.CreateModel(
            name='Categories_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Nombre de Categoria', max_length=200, verbose_name='Nombre de la Categoria')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
                ('area_name', models.ManyToManyField(help_text='Area Corresponde', to='normas.Areas_Normas', verbose_name='Area')),
            ],
            options={
                'verbose_name_plural': '1.Normas - Sub Tipo de Uso',
            },
        ),
        migrations.CreateModel(
            name='Location_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_name', models.CharField(help_text='Nombre Locacion', max_length=200, verbose_name='Locacion')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name_plural': '3.Normas - Locacion',
            },
        ),
        migrations.CreateModel(
            name='Subcategories_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(help_text='Nombre de sub Categoria', max_length=200, verbose_name='sub Categoria')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name_plural': '2.Normas - Tipo De Normativa',
            },
        ),
        migrations.CreateModel(
            name='Master_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma_rne', models.CharField(blank=True, help_text='Nombre RNE - Norma', max_length=50, verbose_name='RNE-Norma')),
                ('norma_name', models.CharField(help_text='Nombre de Norma', max_length=200, verbose_name='Norma')),
                ('validity_date_start', models.DateField(help_text='Fecha Publicacion', verbose_name='Fecha Publicacion')),
                ('keywords', models.CharField(blank=True, help_text='Palabras Clave', max_length=200, verbose_name='Registre palabras clave')),
                ('file', models.FileField(help_text='Suba el archivo o base legal', upload_to=normas.models.upload_file, verbose_name='File')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
                ('area_name', models.ForeignKey(help_text='registro de Tipo de Uso', on_delete=django.db.models.deletion.CASCADE, to='normas.areas_normas', verbose_name='Tipo de Uso')),
                ('category_name', models.ForeignKey(help_text='registro Sub Tipo de Uso', on_delete=django.db.models.deletion.CASCADE, to='normas.categories_normas', verbose_name='Sub Tipo de Uso')),
                ('location_name', models.ForeignKey(help_text='Registro de Locacion', on_delete=django.db.models.deletion.CASCADE, to='normas.location_normas', verbose_name='Locacion')),
                ('subcategory_name', models.ForeignKey(help_text='registro Tipo de Normativa', on_delete=django.db.models.deletion.CASCADE, to='normas.subcategories_normas', verbose_name='Tipo de Normativa')),
            ],
            options={
                'verbose_name_plural': '4.Registrar Normas',
            },
        ),
    ]
